name: CI/CD & Release Workflow

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  publish-tauri:
    name: Build and Publish Tauri App
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest]

    permissions:
      contents: write

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js v22.17.1
        uses: actions/setup-node@v3
        with:
          node-version: 22.17.1

      - name: Install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.18

      - name: Install app dependencies and build it
        run: |
          bun install
          bun tauri build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: tauri-build
          path: src-tauri/target/release/bundle/nsis/*.exe

  release:
    permissions:
      contents: write

    name: Create GitHub Release
    needs: publish-tauri
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  upload-artifacts:
    permissions:
      contents: write

    name: Upload Release Installer
    needs: release
    runs-on: windows-latest
    steps:
      - name: Upload installer EXE
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: src-tauri/target/release/bundle/nsis/tauri-desk-test_${{ github.ref_name }}_x64-setup.exe
          asset_name: tauri-desk-test_${{ github.ref_name }}_x64-setup.exe
          asset_content_type: application/vnd.microsoft.portable-executable
